name: CI

on:
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    #runs-on: [self-hosted]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
          
      - name: ServiceNow DevOps Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          job-name: ${{ github.job }}
          context-github: ${{ toJSON(github) }}
          artifacts: '[{"name": "KIRO-artifact", "version": "1.${{ github.run_number }}.0", "repositoryName": "${{ github.repository }}"}]'
      
      - name: ServiceNow DevOps Register Package
        uses: ServiceNow/servicenow-devops-register-package@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          artifacts: '[{"name": "KIRO-artifact", "version": "1.${{ github.run_number }}.0", "repositoryName": "${{ github.repository }}"}]'
          # Name of the Package that contains list of artifacts
          package-name: SamplePackage
          job-name: ${{ github.job }}
          
  ChangeStep:
     #runs-on: [self-hosted]
     runs-on: ubuntu-latest
     needs: build
     timeout-minutes: 600
     steps:
       - name: Sleep for 30 seconds
         run: Start-Sleep -s 30
         #shell: pwsh
       - name: ServiceNow DevOps Change Automation
         uses: ServiceNow/servicenow-devops-change@v3.1.0
         with:
            # ServiceNow Instance URL
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            job-name: ${{ github.job }}
            context-github: ${{ toJSON(github) }}
            change-request: '{"setCloseCode":"true","attributes":{"short_description":"Github Auto Deploy"}}'
            # This value will be used to resume or abort the pipeline if the change is not created within the mentioned time period in changeCreationTimeOut. 
            abortOnChangeCreationFailure: true  #optional, default is true
            # This value will be used to resume or abort the pipeline after a timeout has occurred in case a change step is still in a pending state.
            abortOnChangeStepTimeout: true # optional, default is true
          

  deploy:
     needs: ChangeStep
     runs-on: ubuntu-latest
     steps:
       - name: Sleep for 30 seconds
         run: Start-Sleep -s 60
         #shell: pwsh
       - name: Run a one-line script
         run : exit 1
